### ISSUE TITLE
Docker for Graphs with R

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/opensnp.org-docker#4]
Ok, so I now figured out that there's a `rocker/hadleyverse` Docker image already which we could use to generate the usage/growth graphs daily via a cronjob. 

What I tried so far (it seemed to work) is run the following from the `opensnp_misc folder`:

`docker run --name plot -v $(pwd):/home/rplots -w /home/rplots rocker/hadleyverse`
in combination with the following command 
`docker exec plot Rscript plotUsers.r`
It then writes the stuff into my mounted directory on the host-machine. 

But what do I now have to do to make this useful for our deployed version? I guess our mountpoints will have to be adjusted to the public-directories on the webserver etc but what else?

**Comment by tsujigiri** [comment]
You could try setting up an _automated build_ at docker hub, so it gets built whenever this repository updates. Then we pull it from the server side and run it via cron. In [openSNP/snpr](https://github.com/openSNP/snpr) we then need a page that includes the graphs, I guess?

**Comment by gedankenstuecke** [comment]
Yes, we'll need a page for that. iirc @philippbayer had a suggestion of where to put it already?

**Comment by philippbayer** [comment]
my suggestion was to delete the Users index, could put Stats there?

**Comment by gedankenstuecke** [comment]
Ah, yes. Good idea, I think the user index is rather useless as it is, maybe do a small "last 10 users" or so? Or keep it but remove from main page?

**Comment by philippbayer** [comment]
new users is on the [news page](https://opensnp.org/news#users) - i keep forgetting about it :)

We could link to the users index from there?

**Comment by gedankenstuecke** [comment]
:+1:

**Comment by gedankenstuecke** [comment]
closing this now, because the issue is solved w/ [growthplots](https://github.com/openSNP/growthplots)

Discussion of the best way to view it can be done in openSNP/snpr/issues/102
